name: minerd
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  sqflite: ^2.0.0+4
  flutter_sound: ^9.2.13+1
  http: ^0.13.6
  shared_preferences: ^2.0.6
  file_picker: ^8.0.6
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  path_provider: ^2.0.7
  permission_handler: ^11.3.1
  url_launcher: ^6.0.9
  flutter_map: ^4.0.0
  latlong2: ^0.8.0
  html: ^0.15.0
  translator: ^0.1.7
  just_audio: ^0.9.22
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/technician_photo.jpg
    - assets/Login_logo.png
    - assets/Minerd_logo.png
    - assets/cloudy.png
    - assets/rainy.png
    - assets/sunny.png
    - assets/default.png
    